# Actions
A = {
    'place-on-map': ['place map'],
    'move': ['move'],
    'change-harvest-loc': ['change harvest location'],
    'change-harvest-tool': ['change harvest tool'],
    'harvest': ['harvest'],
    'harvest-loose-tool': ['harvest loose tool'],
    'get-harvest-wood': ['harvest wood'],
    'get-harvest-stone': ['harvest stone'],
    'get-harvest-coal': ['harvest coal'],
    'get-harvest-ironore': ['harvest iron ore', 'harvest iron-ore', 'harvest ironore'],
    'get-harvest-seeds': ['harvest seeds'],
    'get-harvest-wheat': ['harvest wheat'],
    'get-harvest-sandstone': ['harvest sandstone'],
    'get-harvest-sand': ['harvest sand'],
    'get-harvest-clay': ['harvest clay'],
    'get-harvest-bone': ['harvest bone'],
    'get-harvest-brown-mushroom': ['harvest brown mushroom'],
    'get-harvest-red-mushroom': ['harvest red mushroom'],
    'get-harvest-sugarcane': ['harvest sugarcane', 'harvest sugar cane'],
    'get-harvest-string': ['harvest string'],
    'get-harvest-egg': ['harvest egg'],
    'get-harvest-fish': ['harvest fish'],
    'get-harvest-wool': ['harvest wool'],
    'get-harvest-milk': ['harvest milk'],
    'grow-tallgrass': ['grow tall grass'],
    'make-farmland': ['make farmland'],
    'grow-wheatgrass': ['grow wheat grass'],
    'place': ['place'],
    'craft-wood-plank': ['craft wood plank'],
    'craft-wood-stick': ['craft wood stick'],
    'craft-torch': ['craft torch'],
    'craft-furnace': ['craft furnace'],
    'craft-wood-pickaxe': ['craft wood pickaxe'],
    'craft-wood-axe': ['craft wood axe'],
    'craft-wood-shovel': ['craft wood shovel'],
    'craft-wood-hoe': ['craft wood hoe'],
    'craft-sandstone': ['craft sandstone'],
    'craft-clayblock': ['craft clay'],
    'craft-brick': ['craft brick'],
    'make-sugar': ['make sugar'],
    'make-paper': ['make paper'],
    'make-wool': ['make wool'],
    'craft-bed': ['craft bed'],
    'craft-chest': ['craft chest'],
    'craft-wood-door': ['craft wood door'],
    'craft-iron-door': ['craft iron door'],
    'craft-ladder': ['craft ladder'],
    'craft-fence': ['craft fence'],
    'craft-stone-brick': ['craft stone brick'],
    'craft-ironbar': ['craft iron bar'],
    'craft-glasspane': ['craft glass pane'],
    'make-bread': ['make bread'],
    'craft-shears': ['craft shears'],
    'craft-bowl': ['craft bowl'],
    'craft-bucket': ['craft bucket'],
    'craft-fishingrod': ['craft fishing rod'],
    'craft-bonemeal': ['craft bone meal'],
    'craft-wood-stairs': ['craft wood stairs'],
    'craft-stone-stairs': ['craft stone stairs'],
    'craft-brick-stairs': ['craft brick stairs'],
    'craft-stonebrick-stairs': ['craft stone brick stairs'],
    'make-mushroomstew-1': ['make mushroom stew'],
    'make-mushroomstew-2': ['make mushroom stew'],
    'furnace-cook-fish': ['furnace cook fish'],
    'furnace-fire-brick': ['furnace fire brick'],
    'furnace-make-charcoal': ['furnace make charcoal'],
    'furnace-smelt-iron': ['furnace smelt iron'],
    'furnace-make-glass': ['furnace make glass']
}

# Objects
O = {
    'ironbar': ['iron bar', 'ironbar'],
    'seeds': ['seeds'],
    'brown-mushroom': ['brown mushroom'],
    'sand': ['sand'],
    'bone': ['bone'],
    'fish': ['fish'],
    'bucket': ['bucket'],
    'wood-pickaxe': ['wood pickaxe'],
    'sugar': ['sugar'],
    'string': ['string'],
    'egg': ['egg'],
    'plank': ['plank'],
    'clay': ['clay'],
    'iron': ['iron'],
    'wood-axe': ['wood axe'],
    'coal': ['coal'],
    'bed': ['bed'],
    'glasspane': ['glass pane'],
    'brick': ['brick'],
    'wood-stairs': ['wood stairs'],
    'iron-door': ['iron door'],
    'shears': ['shears'],
    'bread': ['bread'],
    'paper': ['paper'],
    'ladder': ['ladder'],
    'wood-shovel': ['wood shovel'],
    'cookedfish': ['cooked fish'],
    'wood-door': ['wood door'],
    'glass': ['glass'],
    'stick': ['stick'],
    'claybrick': ['clay brick'],
    'cut-sugarcane': ['cut sugar cane', 'cut sugarcane'],
    'sandstone': ['sandstone', 'sand stone'],
    'chest': ['chest'],
    'stonebrick-stairs': ['stone brick stairs'],
    'fishingrod': ['fishing rod'],
    'stonebrick': ['stone brick'],
    'fornace-fuel': ['fornace fuel'],
    'red-mushroom': ['red mushroom'],
    'furnace': ['furnace'],
    'wheat': ['wheat'],
    'ironore': ['iron ore'],
    'stone-stairs': ['stone stairs'],
    'wool': ['wool'],
    'hand': ['hand'],
    'wood': ['wood'],
    'bowl': ['bowl'],
    'milk': ['milk'],
    'brick-stairs': ['brick stairs'],
    'torch': ['torch'],
    'mushroomstew': ['mushroom stew'],
    'stone': ['stone'],
    'bonemeal': ['bone meal'],
    'fence': ['fence'],
    'wood-hoe': ['wood hoe'],
    'clayblock': ['clay block']
}

# Predicates
P = {
    'player-at': ['player at'],
    'thing-at-map': ['thing at map'],
    'placed-thing-at-map': ['placed map'],
    'resource-at-craft': ['resource craft'],
    'craft-empty': ['craft empty'],
    'connect': ['connect'],
    'crafting': ['crafting']
}
